MvcCoreSeguridadEmpleados/Models/Departamento.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcCoreSeguridadEmpleados.Models
{
    [Table("DEPT")]
    public class Departamento
    {
        [Key]
        [Column("DEPT_NO")]
        public int DeptNo { get; set; }
        [Column("DNOMBRE")]
        public string Nombre { get; set; }
        [Column("LOC")]
        public string Loc { get; set; }
    }
}

MvcCoreSeguridadEmpleados/Models/Empleado.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcCoreSeguridadEmpleados.Models
{
    [Table("EMP")]
    public class Empleado
    {
        [Key]
        [Column("EMP_NO")]
        public int IdEmpleado { get; set; }
        [Column("APELLIDO")]
        public string Apellido { get; set; }
        [Column("OFICIO")]
        public string Oficio { get; set; }
        [Column("SALARIO")]
        public int Salario { get; set; }
        [Column("DEPT_NO")]
        public int Dept_no { get; set; }
    }
}

MvcCoreSeguridadEmpleados/Models/ErrorViewModel.cs
namespace MvcCoreSeguridadEmpleados.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreSeguridadEmpleados/Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreSeguridadEmpleados.Filters;
using MvcCoreSeguridadEmpleados.Models;
using MvcCoreSeguridadEmpleados.Repositories;

namespace MvcCoreSeguridadEmpleados.Controllers
{
    public class EmpleadosController : Controller
    {
        private RepositoryEmpleados repo;

        public EmpleadosController(RepositoryEmpleados repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            List<Empleado> empleados = this.repo.GetEmpleados();
            return View(empleados);
        }

        public IActionResult Details(int id)
        {
            Empleado empleado = this.repo.FindEmpleado(id);
            return View(empleado);
        }

        public IActionResult EmpleadosDept(int deptno)
        {
            List<Empleado> empleados = this.repo.FindEmpleadosDept(deptno);
            ViewData["DEPTNO"] = deptno;
            return View(empleados);
        }

        [HttpPost]
        public async Task<IActionResult> EmpleadosDept(int deptno, int salario)
        {
            await this.repo.AumentarSalarioAsync(deptno, salario);
            List<Empleado> empleados = this.repo.FindEmpleadosDept(deptno);
            ViewData["DEPTNO"] = deptno;
            return View(empleados);
        }

        [AuthorizeEmpleados]
        public IActionResult PerfilEmpleado()
        {
            return View();
        }
    }
}

MvcCoreSeguridadEmpleados/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreSeguridadEmpleados.Models;
using System.Diagnostics;

namespace MvcCoreSeguridadEmpleados.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreSeguridadEmpleados/Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using MvcCoreSeguridadEmpleados.Models;
using MvcCoreSeguridadEmpleados.Repositories;
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;

namespace MvcCoreSeguridadEmpleados.Controllers
{
    public class ManagedController : Controller
    {
        private RepositoryEmpleados repo;

        public ManagedController(RepositoryEmpleados repo)
        {
            this.repo = repo;
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(string username, string password)
        {
            Empleado empleado = await this.repo.ExisteEmpleado(username, int.Parse(password));
            if (empleado != null)
            {
                ClaimsIdentity identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme, ClaimTypes.Name, ClaimTypes.Role);
                Claim claimName = new Claim(ClaimTypes.Name, username);
                identity.AddClaim(claimName);
                Claim claimId = new Claim(ClaimTypes.NameIdentifier, empleado.IdEmpleado.ToString());
                identity.AddClaim(claimId);
                Claim claimOficio = new Claim(ClaimTypes.Role, empleado.Oficio);
                identity.AddClaim(claimOficio);
                Claim claimSalario = new Claim("Salario", empleado.Salario.ToString());
                identity.AddClaim(claimSalario);
                Claim claimDepartamento = new Claim("Departamento", empleado.Dept_no.ToString());
                identity.AddClaim(claimDepartamento);
                ClaimsPrincipal userPrincipal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, userPrincipal);
                return RedirectToAction("PerfilEmpleado", "Empleados");
            }
            else
            {
                ViewData["MENSAJE"] = "Usuario/Password incorrectos";
                return View();
            }
        }
        public IActionResult ErrorAcceso()
        {
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
    }
}

MvcCoreSeguridadEmpleados/ViewComponents/MenuDepartamentosViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreSeguridadEmpleados.Repositories;
using MvcCoreSeguridadEmpleados.Models;

namespace MvcCoreSeguridadEmpleados.ViewComponents
{
    public class MenuDepartamentosViewComponent: ViewComponent
    {
        private RepositoryDepartamentos repo;

        public MenuDepartamentosViewComponent(RepositoryDepartamentos repo)
        {
            this.repo = repo;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Departamento> departamentos = this.repo.GetDepartamentos();
            return View(departamentos);
        }
    }
}

MvcCoreSeguridadEmpleados/Views/Empleados/Details.cshtml
@model Empleado

<h4>
    Details Empleado
</h4>

<h4>
    @Model.Apellido @Model.Oficio @Model.Salario
</h4>

MvcCoreSeguridadEmpleados/Views/Empleados/EmpleadosDept.cshtml
@model List<Empleado>

<h4>Vista Empleados</h4>

@{
    int dept = (int)ViewData["DEPTNO"];
}

<form method="post">
    <input type="hidden" value="@dept" />
    <label>Salario: </label>
    <input type="text" name="salario" />
    <button class="btn btn-dark">
        Enviar
    </button>
</form>

@if (Model != null)
{
    <table class="table table-active table-hover w-100 table-bordered text-center">
        <thead>
            <tr>
                <th>Id</th>
                <th>Apellido</th>
                <th>Oficio</th>
                <th>Salario</th>
                <th>Departamento</th>
                <th>Detalles</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Empleado emp in Model)
            {
                <tr>
                    <td>@emp.IdEmpleado</td>
                    <td>@emp.Apellido</td>
                    <td>@emp.Oficio</td>
                    <td>@emp.Salario</td>
                    <td>@emp.Dept_no</td>
                    <td>
                        <a asp-controller="Empleados" asp-action="Details" asp-route-id="@emp.IdEmpleado" class="btn btn-info">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

MvcCoreSeguridadEmpleados/Views/Empleados/Index.cshtml
@model List<Empleado>

<h4>Vista Empleados</h4>

@if (Model != null)
{
    <table class="table table-active table-hover w-100 table-bordered text-center">
        <thead>
            <tr>
                <th>Id</th>
                <th>Apellido</th>
                <th>Oficio</th>
                <th>Salario</th>
                <th>Departamento</th>
                <th>Detalles</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Empleado emp in Model)
            {
                <tr>
                    <td>@emp.IdEmpleado</td>
                    <td>@emp.Apellido</td>
                    <td>@emp.Oficio</td>
                    <td>@emp.Salario</td>
                    <td>@emp.Dept_no</td>
                    <td>
                        <a asp-controller="Empleados" asp-action="Details" asp-route-id="@emp.IdEmpleado" class="btn btn-info">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

MvcCoreSeguridadEmpleados/Views/Empleados/PerfilEmpleado.cshtml
<h4>
    Este es tu perfil @Context.User.Identity.Name
</h4>

<ul class="list-group">
    <li class="list-group-item">
        Oficio: @Context.User.FindFirst(ClaimTypes.Role).Value
    </li>
    <li class="list-group-item">
        Salario: @Context.User.FindFirstValue("Salario")
    </li>
    <li class="list-group-item">
        Departamento: @Context.User.FindFirstValue("Departamento")
    </li>
</ul>

<h4>Todos los claims</h4>

<ul class="list-group">
    @foreach (Claim claim in Context.User.Claims)
    {
        <li class="list-group-item">
            @claim.Type: <b>@claim.Value</b>
        </li>
    }
</ul>

MvcCoreSeguridadEmpleados/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreSeguridadEmpleados/Views/Managed/ErrorAcceso.cshtml
<h4>
    No tiene permisos para acceder
</h4>

MvcCoreSeguridadEmpleados/Views/Managed/Login.cshtml
<h4>
    Login Empleados
</h4>

<form method="post">
    <label>Apellido</label>
    <input type="text" name="username" class="form-control" required />
    <label>Password</label>
    <input type="text" name="password" class="form-control" required />
    <button class="btn btn-warning">
        Login
    </button>
</form>

<h4>
    @ViewData["MENSAJE"]
</h4>

MvcCoreSeguridadEmpleados/Views/Shared/Components/MenuDepartamentos/Default.cshtml
@model List<Departamento>

<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Menú departamentos
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        @foreach (Departamento dept in Model)
        {
            <li>
                <a class="dropdown-item" asp-controller="Empleados" asp-action="EmpleadosDept" asp-route-deptno="@dept.DeptNo">
                    @dept.Nombre
                </a>
            </li>
        }
    </ul>
</div>

MvcCoreSeguridadEmpleados/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreSeguridadEmpleados</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreSeguridadEmpleados.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreSeguridadEmpleados</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @await Component.InvokeAsync("MenuDepartamentos")
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="Index">Empleados</a>
                        </li>
                        <partial name="_MenuEmpleados" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcCoreSeguridadEmpleados - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcCoreSeguridadEmpleados/Views/Shared/_MenuEmpleados.cshtml
@if (Context.User.Identity.IsAuthenticated == false)
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="PerfilEmpleado">Login</a>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Managed" asp-action="Logout">Logout <span style ="color:blue">@Context.User.Identity.Name</span></a>
    </li>
}